apiVersion: apps/v1
kind: Deployment
metadata:
  name: pedidos-veloz-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pedidos-veloz
  template:
    metadata:
      labels:
        app: pedidos-veloz
    spec:
      containers:
        - name: api-gateway
          image: nginx:alpine
          ports:
            - containerPort: 80

        - name: pedidos
          image: nginx:alpine
          ports:
            - containerPort: 80

        - name: pagamentos
          image: nginx:alpine
          ports:
            - containerPort: 80

        - name: estoque
          image: nginx:alpine
          ports:
            - containerPort: 80